steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", 'gcr.io/instant-bonbon-379400/gcpdevops', "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", 'gcr.io/instant-bonbon-379400/gcpdevops']
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/instant-bonbon-379400/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-devops-cluster
  - --namespace=gcp-devops-prod