steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/instant-bonbon-379400', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/instant-bonbon-379400']
images:
  - 'gcr.io/$PROJECT_ID/instant-bonbon-379400'



  instant-bonbon-379400